#!/usr/bin/env python3
"""Regenerate docs/spec/rulings.md from the spec registry. Generated file: never
edit it by hand (CI diffs it)."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from punchmark.spec import all_decisions, spec_version  # noqa: E402


def render() -> str:
    lines = [
        "# Spec rulings",
        "",
        f"Rulings-spec version `{spec_version()}`. Generated by "
        "`tools/render_rulings.py` -- do not edit by hand.",
        "",
    ]
    for d in all_decisions():
        marker = "" if d.status == "active" else f" *({d.status})*"
        lines.append(f"## {d.id}: {d.title}{marker}")
        lines.append("")
        lines.append(d.text.strip())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    out = ROOT / "docs" / "spec" / "rulings.md"
    text = render()
    if "--check" in sys.argv:
        if not out.exists() or out.read_text(encoding="utf-8") != text:
            print(f"{out} is stale; run tools/render_rulings.py", file=sys.stderr)
            return 1
        print(f"{out} is current")
        return 0
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
